language: php

php:
    - 7.1
    - 7.2
    - 7.3

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - yarn install

notifications:
  on_success: always
  on_failure: always

script: vendor/bin/atoum