language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest

before_script:
  - cp .env.example .env
  - composer install
  - php artisan key:generate
  - yarn install

notifications:
  on_success: always
  on_failure: always